"""empty message

Revision ID: 900b3d95f4f9
Revises: 2e5a00cd7aa8
Create Date: 2025-01-01 10:49:48.557281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '900b3d95f4f9'
down_revision = '2e5a00cd7aa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
