"""empty message

Revision ID: d1232fe1923e
Revises: 39275ce3fa5b
Create Date: 2025-01-04 16:16:46.648362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1232fe1923e'
down_revision = '39275ce3fa5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('minigoals_user_id_fkey', 'minigoals', type_='foreignkey')
    op.drop_column('minigoals', 'complete')
    op.drop_column('minigoals', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('minigoals', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('minigoals', sa.Column('complete', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_foreign_key('minigoals_user_id_fkey', 'minigoals', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
