"""empty message

Revision ID: 39275ce3fa5b
Revises: cf9fba03cf2c
Create Date: 2025-01-04 11:29:51.654768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39275ce3fa5b'
down_revision = 'cf9fba03cf2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('goals', 'streak',
               existing_type=sa.INTEGER(),
               default=0,
               nullable=False)
    op.alter_column('goals', 'is_daily',
                default=False)
    op.alter_column('goals', 'meetline',
                default=None)
    op.alter_column('goals', 'complete',
                default=False)
    op.alter_column('subgoals', 'meetline',
                default=None)
    op.alter_column('subgoals', 'is_daily',
                default=False)
    op.alter_column('subgoals', 'streak',
                default=0)
    op.alter_column('subgoals', 'complete',
                default=False)
    op.alter_column('minigoals', 'complete',
                default=False)
    op.add_column('subgoals', sa.Column('meetline', sa.Date(), nullable=True))
    op.drop_column('subgoals', 'meet_by')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subgoals', sa.Column('meet_by', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('subgoals', 'meetline')
    op.alter_column('goals', 'streak',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
